import ExcelJS from 'exceljs';
import Papa from 'papaparse';
import JSZip from 'jszip';
import {Employee} from './domain';
export const fields:Record<string,string>={employee_id:'员工编号',name:'姓名',cycle_id:'盘点批次',review_year:'盘点年度',snapshot_date:'数据快照日期',company_id:'公司编号',company_name:'公司名称',department_id:'二级组织编号',department_name:'二级组织名称',team_id:'三级组织编号',team_name:'三级组织名称',manager_id:'直属上级编号',job_family:'岗位序列',job_title:'岗位名称',job_level:'职级',location:'工作地点',employment_status:'在职状态',hire_date:'入职日期',years_in_role:'现岗位年限',is_manager:'是否管理者',is_key_position:'是否关键岗位',kpi_score:'KPI得分',delivery_score:'交付质量得分',assessment_score:'测评得分',manager_score:'上级能力评分',values_score:'价值观得分',collaboration_score:'协作得分',leadership_score:'领导力得分',learning_score:'学习敏捷度得分',skills:'技能标签',achievement_evidence:'业绩事实',manager_feedback:'上级反馈',development_needs:'发展需求',career_aspiration:'职业意向',mobility_preference:'流动意愿',successor_for_employee_id:'拟接任岗位任职者编号',successor_readiness:'接任准备度',data_source:'数据来源'};
// ExcelJS expects unprefixed SpreadsheetML elements; normalize valid namespace-prefixed exports.
async function compatibleXlsx(buffer:ArrayBuffer){const zip=await JSZip.loadAsync(buffer);for(const [name,entry] of Object.entries(zip.files)){if(name.endsWith('.xml')&&!entry.dir){let xml=await entry.async('string');const match=xml.match(/xmlns:([A-Za-z][\w-]*)="http:\/\/schemas.openxmlformats.org\/spreadsheetml\/2006\/main"/);if(match){const prefix=match[1];xml=xml.replace(new RegExp(`(<\\/?)${prefix}:`,'g'),'$1').replace(match[0],'xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"');zip.file(name,xml);}}}return zip.generateAsync({type:'arraybuffer'});}
export async function parseImport(buffer:ArrayBuffer,filename:string):Promise<Employee[]>{
 let rows:unknown[][]=[];
 if(filename.toLowerCase().endsWith('.csv')){const parsed=Papa.parse<string[]>(new TextDecoder().decode(buffer).replace(/^\uFEFF/,''),{skipEmptyLines:'greedy'});if(parsed.errors.length)throw Error(`CSV格式错误：${parsed.errors[0].message}`);rows=parsed.data;}
 else if(filename.toLowerCase().endsWith('.xlsx')){const wb=new ExcelJS.Workbook();await wb.xlsx.load(await compatibleXlsx(buffer));const sheet=wb.worksheets[0];if(!sheet)throw Error('工作簿没有工作表');if(sheet.rowCount>20001)throw Error('最多导入20000人');sheet.eachRow(row=>{const cells:unknown[]=[];for(let c=1;c<=sheet.columnCount;c++){const cell=row.getCell(c);let v=cell.value;if(v&&typeof v==='object'&&'formula' in v)throw Error('导入表含公式，请先粘贴为值');if(v instanceof Date)v=v.toISOString().slice(0,10);else if(v&&typeof v==='object')v=cell.text;cells.push(v);}rows.push(cells);});}
 else throw Error('请选择.xlsx或.csv文件');
 if(rows.length<2)throw Error('文件至少需要表头和一行员工数据');
 const aliases=Object.fromEntries(Object.entries(fields).map(([k,v])=>[v,k]));const keys=rows[0].map(v=>{const s=String(v??'').trim();return aliases[s]||s;});
 if(new Set(keys).size!==keys.length||keys.some(k=>!k))throw Error('表头不得重复或为空');if(keys.some(k=>['__proto__','prototype','constructor'].includes(k)))throw Error('表头含保留字段');
 return rows.slice(1).map((row,index)=>{if(row.length>keys.length)throw Error(`第${index+2}行列数超过表头`);const e:Record<string,string|number|boolean|null>={};keys.forEach((k,i)=>{const raw=row[i];let value=raw===undefined||raw===null?'':String(raw).trim();if(k.endsWith('_score')||['review_year','years_in_role'].includes(k)){e[k]=value===''?null:Number(value);}else if(['is_manager','is_key_position'].includes(k)){if(!['true','false','TRUE','FALSE','是','否','1','0',''].includes(value))throw Error(`第${index+2}行${k}须为是/否`);e[k]=['true','TRUE','是','1'].includes(value);}else e[k]=value;});return e as Employee;});
}
